### ISSUE TITLE
Todos

### ISSUE THREAD

**Issue by julia-sprenger** [CodeVisionaries/larktools#2]
- [x] extend grammar to multi-line statements @julia-sprenger #7 
- [x] add variable assignments to grammar @julia-sprenger #8 
- [x] extend grammar to arrays (incl basic indexing in arange-style) @gschnabel #6 
- [x] support float point numbers @thomasms #9
- [x] support 10E-1 notation @thomasms #9
- [ ] add grammar support for line comments (to be extended to inline comments at some point) @gschnabel 

Reminder: Don't forget to add tests (pytest).

- [x] make eval functions more flexible (see https://github.com/CodeVisionaries/larktools/pull/6#discussion_r1794939756) s Potentially good to exploit the [visitor pattern](https://lark-parser.readthedocs.io/en/latest/visitors.html) - to be investigated @thomasm @gschnabel 
- [ ] add type hints @gschnabel 
- [ ] logical expression parsing @julia-sprenger (https://github.com/CodeVisionaries/larktools/pull/11)
- [ ] if ... else
- [ ] loops
- [ ] function definitions
